### ISSUE TITLE
於Google drive資料集的資料內容為安全帽並無口罩的圖片

### ISSUE THREAD

**Issue by thinktwice812** [hikariming/virus-mask-dataset#2]
下載Google drive內容( https://drive.google.com/drive/folders/1ByRDDh7ynQucA_06cbGF2jbuc-NHvUYQ?usp=sharing)，解壓縮後發現內容皆為安全帽並無口罩的圖片，請問是否有誤呢?謝謝

**Comment by hikariming** [comment]
因为之前我们还没标记完全，现在图片已经更新了，可以去看看呢
